name: Deploy to AWS
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: |
          npm install
          npm install -g @aws-amplify/cli
          
      - name: Build
        run: |
          npm run build
          
      - name: Deploy to AWS Amplify
        run: |
          amplify pull --appId ${{ secrets.AWS_AMPLIFY_APP_ID }} --envName dev --yes
          amplify push --yes
          amplify publish --yes