name: Deploy to AWS
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Create .env file
        run: |
          touch .env
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
          echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env
          
      - name: Install Dependencies
        run: |
          npm install -g @aws-amplify/cli
          npm install
          
      - name: Configure Amplify
        run: |
          amplify configure project --projectName StockPortfolioApp \
            --envName production \
            --defaultEditor vscode \
            --appId ${{ secrets.AWS_AMPLIFY_APP_ID }} \
            --yes
            
      - name: Initialize Amplify
        run: |
          amplify init --amplify "{\"envName\":\"production\"}" --yes
          
      - name: Build and Deploy
        env:
          AWS_AMPLIFY_APP_ID: ${{ secrets.AWS_AMPLIFY_APP_ID }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          npm run build
          amplify push --yes